# Generated by Django 6.0.7 on 2026-07-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('resource', models.CharField(db_index=True, max_length=150)),
                ('allowed', models.BooleanField()),
                ('remaining', models.IntegerField()),
                ('degraded', models.BooleanField(default=False, help_text='True if this decision was made via fail-safe fallback, not Redis.')),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'al_request_log',
                'indexes': [models.Index(fields=['client_id', 'resource', 'created_at'], name='al_request__client__e0f41c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('resource', models.CharField(db_index=True, max_length=150)),
                ('bucket_start', models.DateTimeField(help_text='Start of the hourly bucket (UTC).')),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('allowed_requests', models.PositiveIntegerField(default=0)),
                ('rejected_requests', models.PositiveIntegerField(default=0)),
                ('degraded_requests', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'al_usage_aggregate',
                'indexes': [models.Index(fields=['client_id', 'resource', 'bucket_start'], name='al_usage_ag_client__16101a_idx')],
                'unique_together': {('client_id', 'resource', 'bucket_start')},
            },
        ),
    ]
