# Generated by Django 6.0.7 on 2026-07-20 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('fail_policy', models.CharField(choices=[('FAIL_OPEN', 'Fail Open'), ('FAIL_CLOSED', 'Fail Closed')], default='FAIL_OPEN', help_text='Behavior when Redis is unavailable for this client.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rl_client',
            },
        ),
        migrations.CreateModel(
            name='ClientLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(db_index=True, max_length=150)),
                ('limit', models.PositiveIntegerField(help_text='Max requests allowed per window.')),
                ('window_seconds', models.PositiveIntegerField(help_text='Rolling window size in seconds.')),
                ('strategy', models.CharField(choices=[('SLIDING_WINDOW', 'Sliding Window Counter'), ('TOKEN_BUCKET', 'Token Bucket')], default='SLIDING_WINDOW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_configs', to='rate_limiter.client')),
            ],
            options={
                'db_table': 'rl_client_limit_config',
                'indexes': [models.Index(fields=['client', 'resource'], name='rl_client_l_client__22ace8_idx')],
                'unique_together': {('client', 'resource')},
            },
        ),
    ]
